version: '3.7'

services:
  scanner:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: .
      target: scanner
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: scanner
    restart: always
  webserver:
    build: 
      context: .
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: webserver
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - scanner
  http-api:
    build: 
      context: .
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: http-api
    # ports: 
    #   - '84:84'
    restart: always
    depends_on:
      - scanner
  rating:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
    build: 
      context: .
      target: rating
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: rating
      NODE_OPTIONS: '--max-old-space-size=8192'
      TF_ENABLE_ONEDNN_OPTS: '1'
    restart: always
    depends_on:
      - scanner