version: '3.7'

services:
  pgdb:
    build: 
      context: ./postgres
    volumes: 
      - ${DOCKER_POSTGRES_CUSTOM_MOUNT}:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # network_mode: host
  webserver:
    build: 
      context: .
    environment: 
      DB_HOST: pgdb
      PROCESS_NAME: webserver
    depends_on: 
      - pgdb
    ports: 
      - '80:80'
      - '3001:3001'
    restart: always
  scanner:
    build: 
      context: .
    environment: 
      DB_HOST: pgdb
      PROCESS_NAME: scanner
    depends_on: 
      - pgdb
    restart: always
  rating:
    build: 
      context: .
    environment: 
      DB_HOST: pgdb
      PROCESS_NAME: rating
    depends_on: 
      - pgdb
    restart: always
    volumes: 
      - './temp-screencaps:/app/temp-screencaps'