version: '3.9'

services:
  webserver:
    image: ${IMAGE_REPO:-dummy}/shepherd-webserver:${TARGET:-prod}
    build: 
      context: .
      target: ${TARGET:-prod}
    environment: 
      DB_HOST: ${PGDB:-pgdb}
      PROCESS_NAME: webserver
    ports: 
      - '80:80'
    restart: always
  http-api:
    image: ${IMAGE_REPO:-dummy}/shepherd-http-api:${TARGET:-prod}
    build: 
      context: .
      target: ${TARGET:-prod}
    environment: 
      DB_HOST: ${PGDB:-pgdb}
      PROCESS_NAME: http-api
    ports: 
      - '84:84'
    restart: always
  scanner:
    image: ${IMAGE_REPO:-dummy}/shepherd-scanner:${TARGET:-prod}
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: .
    environment: 
      DB_HOST: ${PGDB:-pgdb}
      PROCESS_NAME: scanner
    restart: always
  rating:
    image: ${IMAGE_REPO:-dummy}/shepherd-rating:${TARGET:-prod}
    hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
    build: 
      context: .
    environment: 
      DB_HOST: ${PGDB:-pgdb}
      PROCESS_NAME: rating
      NODE_OPTIONS: '--max-old-space-size=8192'
    restart: always