version: '3.7'

# x-aws-cluster: ECS cluster ID
x-aws-vpc: arn:aws:ec2:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:vpc/${AWS_VPC_ID}
# x-aws-loadbalancer: ${ELB_ARN}

services:
  webserver:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:webserver
    platform: linux/amd64
    logging:
      driver: awslogs
      options:
        awslogs-group: shepherd-services
        # awslogs-format: json/emf
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
  http-api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:http-api
    platform: linux/amd64
    logging:
      options:
        awslogs-group: shepherd-services
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G # (2 vCPU) Between 4 GB and 16 GB in 1 GB increments
  indexer:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:indexer
    platform: linux/amd64
    logging:
      options:
        awslogs-group: shepherd-services    
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
  feeder:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:feeder
    platform: linux/amd64
    logging:
      options:
        awslogs-group: shepherd-services    
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
    environment:
      AWS_FEEDER_QUEUE: ${AWS_FEEDER_QUEUE}
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-feeder-q'
  fetchers:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:fetchers
    platform: linux/amd64
    logging:
      options:
        awslogs-group: shepherd-services    
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 60
    environment:
      AWS_FEEDER_QUEUE: ${AWS_FEEDER_QUEUE}
      AWS_INPUT_BUCKET: ${AWS_INPUT_BUCKET}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-feeder-q'
      - Effect: Allow
        Action: 's3:*'
        Resource: 'arn:aws:s3:::${AWS_INPUT_BUCKET}/*'

  plugin:
    container_name: ${PLUGIN:-nsfw} # not implemented in docker ecs yet
    logging:
      options:
        awslogs-group: shepherd-services    
    depends_on:
      - indexer
    # x-aws-* doesn't get created when this comes from the extended file. bug!
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:*'
      - Effect: Allow
        Action: 's3:*'
        Resource: 
        - 'arn:aws:s3:::${AWS_INPUT_BUCKET}/*'
        - 'arn:aws:s3:::${AWS_INPUT_BUCKET}'

networks:
  default:
    external: true
    name: ${AWS_SECURITY_GROUP_ID}