version: '3.7'

services:
  pgdb:
    # image: ${IMAGE_REPO:-dummy}/shepherd-pgdb:${TARGET:-prod}
    build: 
      context: ./postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 4G
    #   update_config:
    #     order: stop-first # ecs: unsupported
  scanner:
    depends_on: 
      - pgdb
  webserver:
    depends_on: 
      - scanner
  http-api:
    depends_on: 
      - scanner
  rating:
    depends_on: 
      - scanner
volumes:
  pgdata:
    # driver_opts:
    #   performance-mode: maxIO
    #   throughput-mode: bursting