version: '3.7'

services:
  pgdb:
    build: 
      context: ./postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  scanner:
    depends_on: 
      - pgdb
  s3-local:
    image: bitnami/minio:latest
    # volumes:
    #   - minio:/data
    ports:
      # - '9000:9000'
      - '9001:9001' # for UI
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
      # MINIO_FORCE_NEW_KEYS: 'yes'
      MINIO_DEFAULT_BUCKETS: shepherd-input-mod-local:public
  sqs-local:
    build: 
      context: ./sqs-local
    ports:
      # - '9324:9324'
      - '9325:9325' # for UI
  feeder:
    environment:
      SQS_LOCAL: 'yes'
      AWS_ACCESS_KEY_ID: dummy 
      AWS_SECRET_ACCESS_KEY: dummytoo 
      AWS_FEEDER_QUEUE: http://sqs-local:9324/000000000000/shepherd-feeder-q
    depends_on:
      - sqs-local
  fetchers:
    environment:
      SQS_LOCAL: 'yes'
      AWS_ACCESS_KEY_ID: dummy 
      AWS_SECRET_ACCESS_KEY: dummytoo 
      AWS_FEEDER_QUEUE: http://sqs-local:9324/000000000000/shepherd-feeder-q
    depends_on:
      - sqs-local
      - s3-local
volumes:
  pgdata:
  minio:
