version: '3.7'

# x-aws-cluster: ECS cluster ID
x-aws-vpc: ${AWS_VPC_ARN}
# x-aws-loadbalancer: ARN of an existing LoadBalancer

services:
  webserver:
    image: ${IMAGE_REPO:-dummy}/shepherd-webserver:${IMAGE_TAG:-latest}
  http-api:
    image: ${IMAGE_REPO:-dummy}/shepherd-http-api:${IMAGE_TAG:-latest}
  scanner:
    image: ${IMAGE_REPO:-dummy}/shepherd-scanner:${IMAGE_TAG:-latest}
  rating:
    image: ${IMAGE_REPO:-dummy}/shepherd-rating:${IMAGE_TAG:-latest}
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G

networks:
  # need 2, private and public security groups/subnets here
  default:
    external: true
    name: ${AWS_SECURITY_GROUP_ID}

x-aws-cloudformation:
  Resources:
    RatingTaskDefinition:
      Properties:
        ContainerDefinitions:
          - LinuxParameters:
              MaxSwap: 61440
              # Swappiness: 60