version: '3.9'

services:
  webserver:
    build: 
      context: .
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: webserver
    ports: 
      - '80:80'
    restart: always
  http-api:
    build: 
      context: .
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: http-api
    ports: 
      - '84:84'
    restart: always
  scanner:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: .
      target: scanner
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: scanner
    restart: always
  rating:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
    build: 
      context: .
      target: rating
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: rating
      NODE_OPTIONS: '--max-old-space-size=8192'
    restart: always