version: '3.7'

services:
  scanner:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: ./apps
      target: scanner
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: scanner
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    restart: always
  webserver:
    build: 
      context: ./apps
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: webserver
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - scanner
  http-api:
    build: 
      context: ./apps
      target: web
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: http-api
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    # ports: 
    #   - '84:84'
    restart: always
    depends_on:
      - scanner
  feeder:
    build:
      context: ./apps
      target: feeder
    environment:
      PROCESS_NAME: feeder
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    depends_on: 
      - scanner
  fetchers:
    build: 
      context: ./apps
      target: fetchers
    environment:
      PROCESS_NAME: fetchers
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
  # rating0:
  #   hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
  #   build: 
  #     context: ./apps
  #     target: rating
  #   environment: 
  #     DB_HOST: ${DB_HOST:-pgdb}
  #     PROCESS_NAME: rating
  #     SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
  #     NODE_OPTIONS: '--max-old-space-size=8192'
  #     TF_ENABLE_ONEDNN_OPTS: '1'
  #     TASK_ID: 0
  #   # deploy:
  #   #   mode: replicated
  #   #   replicas: 5
  #   restart: always
  #   depends_on:
  #     - scanner
  # rating1:
  #   hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
  #   build: 
  #     context: ./apps
  #     target: rating
  #   environment: 
  #     DB_HOST: ${DB_HOST:-pgdb}
  #     PROCESS_NAME: rating
  #     SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
  #     NODE_OPTIONS: '--max-old-space-size=8192'
  #     TF_ENABLE_ONEDNN_OPTS: '1'
  #     TASK_ID: 1
  #   restart: always
  #   depends_on:
  #     - scanner
  # rating2:
  #   hostname: ${IMAGE_REPO:-dummy}-shepherd-rating
  #   build: 
  #     context: ./apps
  #     target: rating
  #   environment: 
  #     DB_HOST: ${DB_HOST:-pgdb}
  #     PROCESS_NAME: rating
  #     SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
  #     NODE_OPTIONS: '--max-old-space-size=8192'
  #     TF_ENABLE_ONEDNN_OPTS: '1'
  #     TASK_ID: 2
  #   restart: always
  #   depends_on:
  #     - scanner