version: '3.7'

services:
  pgdb:
    build: 
      context: ./postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  scanner:
    depends_on: 
      - pgdb
  sqs-local:
    build: 
      context: ./sqs-local
    ports:
      # - '9324:9324'
      - '9325:9325' # for UI
  feeder:
    environment:
      SQS_LOCAL: 'yes'
      AWS_ACCESS_KEY_ID: dummy 
      AWS_SECRET_ACCESS_KEY: dummytoo 
      AWS_FEEDER_QUEUE: http://sqs-local:9324/000000000000/shepherd-feeder-q
    depends_on:
      - sqs-local
  fetchers:
    environment:
      SQS_LOCAL: 'yes'
      AWS_ACCESS_KEY_ID: dummy 
      AWS_SECRET_ACCESS_KEY: dummytoo 
      AWS_FEEDER_QUEUE: http://sqs-local:9324/000000000000/shepherd-feeder-q
    depends_on:
      - sqs-local
volumes:
  pgdata:
