version: '3.7'

services:
  scanner:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: ./apps
      target: scanner
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: scanner
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    restart: always
  webserver:
    build: 
      context: ./apps
      target: webserver
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: webserver
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - scanner
  http-api:
    build: 
      context: ./apps
      target: http-api
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: http-api
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      SLACK_POSITIVE: ${SLACK_POSITIVE}
    # ports: 
    #   - '84:84'
    restart: always
    depends_on:
      - scanner
  feeder:
    build:
      context: ./apps
      target: feeder
    environment:
      PROCESS_NAME: feeder
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    depends_on: 
      - scanner
  fetchers:
    build: 
      context: ./apps
      target: fetchers
    environment:
      PROCESS_NAME: fetchers
      DB_HOST: ${DB_HOST:-pgdb}
      STREAMS_PER_FETCHER: ${STREAMS_PER_FETCHER:-50}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    depends_on:
      - scanner
  plugin:
    extends:
      file: ./apps/${PLUGIN:-nsfw}/docker-compose.yml
      service: ${PLUGIN:-nsfw}
