version: '3.7'

# x-aws-cluster: ECS cluster ID
x-aws-vpc: arn:aws:ec2:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:vpc/${AWS_VPC_ID}
# x-aws-loadbalancer: ${ELB_ARN}

services:
  webserver:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-webserver:${IMAGE_TAG:-latest}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
  http-api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-http-api:${IMAGE_TAG:-latest}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
  scanner:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-scanner:${IMAGE_TAG:-latest}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
  feeder:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-feeder:${IMAGE_TAG:-latest}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
    environment:
      AWS_FEEDER_QUEUE: ${AWS_FEEDER_QUEUE}
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-feeder-q'
  fetchers:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-fetchers:${IMAGE_TAG:-latest}
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
    environment:
      AWS_FEEDER_QUEUE: ${AWS_FEEDER_QUEUE}
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-feeder-q'
      
  # rating0:
  #   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-rating:${IMAGE_TAG:-latest}
  #   platform: linux/amd64
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4.0'
  #         memory: 30G
  # rating1:
  #   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-rating:${IMAGE_TAG:-latest}
  #   platform: linux/amd64
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4.0'
  #         memory: 30G
  # rating2:
  #   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd-rating:${IMAGE_TAG:-latest}
  #   platform: linux/amd64
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4.0'
  #         memory: 30G

networks:
  default:
    external: true
    name: ${AWS_SECURITY_GROUP_ID}