version: '3.7'

services:
  indexer:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-indexer
    build: 
      context: ./services
      target: indexer
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: indexer
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      GQL_URL: ${GQL_URL:-https://arweave.net/graphql}
      GQL_URL_SECONDARY: ${GQL_URL_SECONDARY:-https://arweave-search.goldsky.com/graphql}
    restart: always
  webserver:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-webserver
    build: 
      context: ./services
      target: webserver
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: webserver
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      SLACK_POSITIVE: ${SLACK_POSITIVE:-}
      SLACK_PROBE: ${SLACK_PROBE:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      GQL_URL: ${GQL_URL:-https://arweave.net/graphql}
      GQL_URL_SECONDARY: ${GQL_URL_SECONDARY:-https://arweave-search.goldsky.com/graphql}
      BLACKLIST_ALLOWED: ${BLACKLIST_ALLOWED:-}
      RANGELIST_ALLOWED: ${RANGELIST_ALLOWED:-}
      GW_URLS: ${GW_URLS:-}
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - indexer
    # mem_limit: 2g
  http-api:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-http-api
    build: 
      context: ./services
      target: http-api
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: http-api
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      SLACK_POSITIVE: ${SLACK_POSITIVE}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      GQL_URL: ${GQL_URL:-https://arweave.net/graphql}
      GQL_URL_SECONDARY: ${GQL_URL_SECONDARY:-https://arweave-search.goldsky.com/graphql}
    # ports: 
    #   - '84:84'
    restart: always
    # depends_on:
    #   - indexer
  feeder:
    build:
      context: ./services
      target: feeder
    environment:
      PROCESS_NAME: feeder
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
    depends_on: 
      - indexer
  fetchers:
    build: 
      context: ./services
      target: fetchers
    environment:
      PROCESS_NAME: fetchers
      DB_HOST: ${DB_HOST:-pgdb}
      STREAMS_PER_FETCHER: ${STREAMS_PER_FETCHER:-50}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
    depends_on:
      - indexer
  
