version: '3.7'

services:
  dbpostgres:
    build: 
      context: ./postgres
    volumes: 
      - ${DOCKER_POSTGRES_CUSTOM_MOUNT}:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # network_mode: host
  app:
    build: 
      context: .
    environment: 
      DB_HOST: dbpostgres
    depends_on: 
      - dbpostgres
    ports: 
      - '80:80'
      - '3001:3001'
    restart: always