version: '3.7'

services:
  pgdb:
    build: 
      context: ./postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  scanner:
    depends_on: 
      - pgdb
volumes:
  pgdata:
