version: '3.7'

services:

  nsfw:
    extends: 
      file: ./docker-compose.yml
      service: nsfw
    depends_on:
      - scanner
    # AWS configs ##
    image: ${AWS_ACCOUNT_ID:-acc}.dkr.ecr.${AWS_DEFAULT_REGION:-reg}.amazonaws.com/shepherd:nsfw

    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
      update_config:
        parallelism: 10
        # order: start-first #unsupported
      replicas: 10
      x-aws-autoscaling:
        min: 2
        max: 20
        cpu: 50
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-input-q'
      - Effect: Allow
        Action: 's3:*'
        Resource: 'arn:aws:s3:::${AWS_INPUT_BUCKET}/*'
