version: '3.7'

services:

  nsfw:
    extends: 
      file: ./docker-compose.base.yml
      service: nsfw
    environment:
      SQS_LOCAL: 'no'
      S3_LOCAL: 'no'
      AWS_SQS_INPUT_QUEUE: ${AWS_SQS_INPUT_QUEUE}
      AWS_INPUT_BUCKET: ${AWS_INPUT_BUCKET}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    # AWS configs ##
    image: ${AWS_ACCOUNT_ID:-acc}.dkr.ecr.${AWS_DEFAULT_REGION:-reg}.amazonaws.com/shepherd:nsfw
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
      replicas: 1 # initial scaling & needed for update_config
      # update_config:
      #   parallelism: 2
      #   # order: start-first # unsupported for ecs
      x-aws-autoscaling:
        min: 1
        max: 100
        cpu: 40
    # # cannot add the PluginTaskRole here in an extended compose file. bug?
    # x-aws-role:
    #   Version: '20....
