version: '3.7'

services:

  plugin:
    hostname: ${IMAGE_REPO:-local}-nsfw-container
    build: 
      context: .
      target: ${TFJS:-tfjs} # tfjs to rebuild node bindings. set to no-tfjs to skip
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      NUM_FILES: ${NUM_FILES:-50}
      TOTAL_FILESIZE_GB: ${TOTAL_FILESIZE_GB:-10}
    restart: always
    # depends_on:
    #   - indexer
