version: '3.7'

services:

  plugin:
    hostname: ${IMAGE_REPO:-local}-nsfw-container
    build: 
      context: .
      target: ${TARGET_NSFW:-nsfw} # nsfw to rebuild tfjs node bindings. set to no-nsfw to skip
    environment:
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      NUM_FILES: ${NUM_FILES:-50}
      TOTAL_FILESIZE_GB: ${TOTAL_FILESIZE_GB:-10}
      
      AWS_SQS_INPUT_QUEUE: ${AWS_SQS_INPUT_QUEUE}
      AWS_INPUT_BUCKET: ${AWS_INPUT_BUCKET}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      HTTP_API_URL: http://http-api.shepherd.local:84/postupdate

    # AWS configs ##
    image: ${AWS_ACCOUNT_ID:-acc}.dkr.ecr.${AWS_DEFAULT_REGION:-reg}.amazonaws.com/shepherd:nsfw
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
      x-aws-autoscaling:
        min: 1
        max: 10
        cpu: 40
    # # cannot add the PluginTaskRole here in an extended compose file. bug?
    # x-aws-role:
    #   Version: '20....
