version: '3.7'

services:

  nsfw:
    hostname: ${IMAGE_REPO:-host}-nsfw-container
    image: ${AWS_ACCOUNT_ID:-acc}.dkr.ecr.${AWS_DEFAULT_REGION:-reg}.amazonaws.com/shepherd:nsfw
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      
      SQS_LOCAL: ${SQS_LOCAL:-yes}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-dummy}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-dummytoo}
      AWS_SQS_INPUT_QUEUE: ${AWS_SQS_INPUT_QUEUE:-http://sqs-local:9324/000000000000/shepherd-s3-events}
      # AWS_INPUT_BUCKET: ${AWS_INPUT_BUCKET:-}
    restart: always
    # depends_on:
    #   - scanner

  sqs-local-test:
    extends:
      file: ../../docker-compose.test.yml
      service: sqs-local-test