version: '3.7'

services:

  plugin:
    extends: 
      file: ./docker-compose.base.yml
      service: plugin
    deploy:
      mode: replicated
      replicas: 4
    environment: 
      SQS_LOCAL: 'yes'
      S3_LOCAL: 'yes'
      AWS_ACCESS_KEY_ID: minioroot
      AWS_SECRET_ACCESS_KEY: minioroot
      # AWS_DEFAULT_REGION: dummy-region
      AWS_SQS_INPUT_QUEUE: http://sqs-local:9324/000000000000/shepherd-s3-events
      AWS_INPUT_BUCKET: shepherd-input-mod-local
      S3_LOCAL_ENDPOINT: http://s3-local:9000
      HTTP_API_URL: http://http-api:84/postupdate
