version: '3.7'

services:

  nsfw:
    hostname: ${IMAGE_REPO:-host}-nsfw-container
    image: ${AWS_ACCOUNT_ID:-acc}.dkr.ecr.${AWS_DEFAULT_REGION:-reg}.amazonaws.com/shepherd:nsfw
    build: 
      context: ..
      dockerfile: ./nsfw/Dockerfile
      # target: rating
    environment: 
      DB_HOST: ${DB_HOST:-pgdb}
      PROCESS_NAME: rating
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      
      SQS_LOCAL: ${SQS_LOCAL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-dummy}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-dummytoo}
      AWS_SQS_INPUT_QUEUE: ${AWS_SQS_INPUT_QUEUE:-http://sqs-local:9324/000000000000/shepherd-s3-events}
      # AWS_INPUT_BUCKET: ${AWS_INPUT_BUCKET:-}
      
    restart: always
    # depends_on:
    #   - scanner
    
    # AWS configs ##
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 30G
      x-aws-autoscaling:
        min: 1
        max: 20
        cpu: 75
    x-aws-role:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action: 'sqs:*' 
        Resource: 'arn:aws:sqs:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:shepherd-input-q'
      - Effect: Allow
        Action: 's3:*'
        Resource: 'arn:aws:s3:::${AWS_INPUT_BUCKET}/*'
