events {}

http {
  # TODO: TLS termination

  server {
    listen 80;

    # TODO: proxy to webserver-next (blacklist serving)
    # TODO: proxy to http-api (classifier result ingestion, port 84)
  }
}
