name: Gitopia Mirror

on:
  push:
    branches: [mirror]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Gitopia Mirror Action
        uses: gitopia/gitopia-mirror-action@v0.1.2
        with:
          gitopiaWallet: "${{ secrets.GITOPIA_WALLET }}"
          branch: "mirror"
          remoteUrl: "gitopia://aoaJNC8NcKVfgwaUj6kyJi2hKrVGUsRHCGf8RhKnsic/ar-blacklist"